const CONSTANTS = {
  ACCESS_TOKEN_EXPIRY: '24h',
  REFRESH_TOKEN_EXPIRY: '14d',
  REFRESH_RATE: 24 * 60 * 60 * 1000,
  PAGINATION_LIMIT:8,
  // ACCESS_TOKEN_EXPIRY: '2m',
  // REFRESH_TOKEN_EXPIRY: '8m',
};

module.exports = CONSTANTS;
